### ISSUE TITLE
Update Travis CI

### ISSUE THREAD

**Issue by GreenPioneer** [greenpioneersolutions/auto-parse#13]
``` yml
language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - "node"
os:
  - linux
  - osx
script:
  - npm test
```
